// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.5.1
// source: xres/xres_header.proto

package xres

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XresloaderHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XresVer     string `protobuf:"bytes,1,opt,name=xres_ver,json=xresVer,proto3" json:"xres_ver,omitempty"`
	DataVer     string `protobuf:"bytes,2,opt,name=data_ver,json=dataVer,proto3" json:"data_ver,omitempty"`
	Count       uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	HashCode    string `protobuf:"bytes,4,opt,name=hash_code,json=hashCode,proto3" json:"hash_code,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *XresloaderHeader) Reset() {
	*x = XresloaderHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xres_xres_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XresloaderHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XresloaderHeader) ProtoMessage() {}

func (x *XresloaderHeader) ProtoReflect() protoreflect.Message {
	mi := &file_xres_xres_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XresloaderHeader.ProtoReflect.Descriptor instead.
func (*XresloaderHeader) Descriptor() ([]byte, []int) {
	return file_xres_xres_header_proto_rawDescGZIP(), []int{0}
}

func (x *XresloaderHeader) GetXresVer() string {
	if x != nil {
		return x.XresVer
	}
	return ""
}

func (x *XresloaderHeader) GetDataVer() string {
	if x != nil {
		return x.DataVer
	}
	return ""
}

func (x *XresloaderHeader) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *XresloaderHeader) GetHashCode() string {
	if x != nil {
		return x.HashCode
	}
	return ""
}

func (x *XresloaderHeader) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type XresloaderDatablocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header          *XresloaderHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DataBlock       [][]byte          `protobuf:"bytes,2,rep,name=data_block,json=dataBlock,proto3" json:"data_block,omitempty"`
	DataMessageType string            `protobuf:"bytes,3,opt,name=data_message_type,json=dataMessageType,proto3" json:"data_message_type,omitempty"`
}

func (x *XresloaderDatablocks) Reset() {
	*x = XresloaderDatablocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xres_xres_header_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XresloaderDatablocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XresloaderDatablocks) ProtoMessage() {}

func (x *XresloaderDatablocks) ProtoReflect() protoreflect.Message {
	mi := &file_xres_xres_header_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XresloaderDatablocks.ProtoReflect.Descriptor instead.
func (*XresloaderDatablocks) Descriptor() ([]byte, []int) {
	return file_xres_xres_header_proto_rawDescGZIP(), []int{1}
}

func (x *XresloaderDatablocks) GetHeader() *XresloaderHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *XresloaderDatablocks) GetDataBlock() [][]byte {
	if x != nil {
		return x.DataBlock
	}
	return nil
}

func (x *XresloaderDatablocks) GetDataMessageType() string {
	if x != nil {
		return x.DataMessageType
	}
	return ""
}

var File_xres_xres_header_proto protoreflect.FileDescriptor

var file_xres_xres_header_proto_rawDesc = []byte{
	0x0a, 0x16, 0x78, 0x72, 0x65, 0x73, 0x2f, 0x78, 0x72, 0x65, 0x73, 0x5f, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72,
	0x65, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x22, 0x9e, 0x01, 0x0a, 0x11,
	0x78, 0x72, 0x65, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x78, 0x72, 0x65, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x78, 0x72, 0x65, 0x73, 0x56, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa0, 0x01, 0x0a,
	0x15, 0x78, 0x72, 0x65, 0x73, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x3c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x65,
	0x73, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x78, 0x72, 0x65, 0x73, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x64, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x07, 0x5a, 0x05, 0x2f, 0x78, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xres_xres_header_proto_rawDescOnce sync.Once
	file_xres_xres_header_proto_rawDescData = file_xres_xres_header_proto_rawDesc
)

func file_xres_xres_header_proto_rawDescGZIP() []byte {
	file_xres_xres_header_proto_rawDescOnce.Do(func() {
		file_xres_xres_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_xres_xres_header_proto_rawDescData)
	})
	return file_xres_xres_header_proto_rawDescData
}

var file_xres_xres_header_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xres_xres_header_proto_goTypes = []interface{}{
	(*XresloaderHeader)(nil),     // 0: org.xresloader.pb.xresloader_header
	(*XresloaderDatablocks)(nil), // 1: org.xresloader.pb.xresloader_datablocks
}
var file_xres_xres_header_proto_depIdxs = []int32{
	0, // 0: org.xresloader.pb.xresloader_datablocks.header:type_name -> org.xresloader.pb.xresloader_header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xres_xres_header_proto_init() }
func file_xres_xres_header_proto_init() {
	if File_xres_xres_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xres_xres_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XresloaderHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xres_xres_header_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XresloaderDatablocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xres_xres_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xres_xres_header_proto_goTypes,
		DependencyIndexes: file_xres_xres_header_proto_depIdxs,
		MessageInfos:      file_xres_xres_header_proto_msgTypes,
	}.Build()
	File_xres_xres_header_proto = out.File
	file_xres_xres_header_proto_rawDesc = nil
	file_xres_xres_header_proto_goTypes = nil
	file_xres_xres_header_proto_depIdxs = nil
}
