// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.5.1
// source: cs_login.proto

package csproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type CS_LOGIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex     string   `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Account *Account `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *CS_LOGIN) Reset() {
	*x = CS_LOGIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS_LOGIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_LOGIN) ProtoMessage() {}

func (x *CS_LOGIN) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_LOGIN.ProtoReflect.Descriptor instead.
func (*CS_LOGIN) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{1}
}

func (x *CS_LOGIN) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CS_LOGIN) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *CS_LOGIN) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type SC_LOGIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success int32 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SC_LOGIN) Reset() {
	*x = SC_LOGIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC_LOGIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_LOGIN) ProtoMessage() {}

func (x *SC_LOGIN) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_LOGIN.ProtoReflect.Descriptor instead.
func (*SC_LOGIN) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{2}
}

func (x *SC_LOGIN) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

var File_cs_login_proto protoreflect.FileDescriptor

var file_cs_login_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x22, 0x5a, 0x0a, 0x08, 0x43, 0x53, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x28, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x24, 0x0a, 0x08, 0x53, 0x43, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x63, 0x73, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_login_proto_rawDescOnce sync.Once
	file_cs_login_proto_rawDescData = file_cs_login_proto_rawDesc
)

func file_cs_login_proto_rawDescGZIP() []byte {
	file_cs_login_proto_rawDescOnce.Do(func() {
		file_cs_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_login_proto_rawDescData)
	})
	return file_cs_login_proto_rawDescData
}

var file_cs_login_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cs_login_proto_goTypes = []interface{}{
	(*Account)(nil),  // 0: proto.account
	(*CS_LOGIN)(nil), // 1: proto.CS_LOGIN
	(*SC_LOGIN)(nil), // 2: proto.SC_LOGIN
}
var file_cs_login_proto_depIdxs = []int32{
	0, // 0: proto.CS_LOGIN.account:type_name -> proto.account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cs_login_proto_init() }
func file_cs_login_proto_init() {
	if File_cs_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS_LOGIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC_LOGIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_login_proto_goTypes,
		DependencyIndexes: file_cs_login_proto_depIdxs,
		MessageInfos:      file_cs_login_proto_msgTypes,
	}.Build()
	File_cs_login_proto = out.File
	file_cs_login_proto_rawDesc = nil
	file_cs_login_proto_goTypes = nil
	file_cs_login_proto_depIdxs = nil
}
